---
checksums:
  go1.20.6.darwin-arm64.tar.gz: sha256:1163be1998835a13f00dfc869a8e3cdebf86984ad41ff2fff43e35ac2a0d8344
  go1.20.6.linux-amd64.tar.gz: sha256:b945ae2bb5db01a0fb4786afde64e6fbab50b67f6fa0eb6cfa4924f16a7ff1eb

go_version: 1.20.6
goos: "{{ _goos_map[ansible_os_family | lower] }}"
goarch: "{{ _goarch_map[ansible_architecture] }}"
go_tarball: go{{ go_version }}.{{ goos }}-{{ goarch }}.tar.gz
go_url: https://go.dev/dl/{{ go_tarball }}
go_checksum: "{{ checksums[go_tarball] }}"
go_install_dir: /opt
