---
- name: check for google tools mount
  stat:
    path: "/Volumes/GoogleDrive/My Drive/Tools"
  register: tools_path

- name: install tools
  copy:
    src: "{{ item.source }}"
    dest: "{{ user_home }}/bin/{{ item.name }}"
    mode: "0755"
  loop:
    - {name: "d42", source: "/Volumes/GoogleDrive/My Drive/Tools/D42/d42"}
  when: tools_path.stat.exists
