go_arch_map:
  "x86_64": "amd64"
go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

go_os_map:
  "Linux": "linux"
go_os: "{{ go_os_map[ansible_system] | default(ansible_system|lower) }}"
go_tarball: "{{ tarball_dir }}/{{ go_url|basename }}"