
- name: download rustup
  ansible.builtin.get_url:
    url: "{{ rustup_url }}"
    dest: "{{ rustup_tarball }}"
    checksum: "{{ rustup_checksum }}"
  become: true
  register: rustup_download

- name: install rustup
  block:
    - name: temp dir
      ansible.builtin.tempfile:
        state: directory
        suffix: rustup
      register: rustup_tempdir

    - name: extract rustup
      ansible.builtin.unarchive:
        src: "{{ rustup_tarball }}"
        dest: "{{ rustup_tempdir.path }}"
        extra_opts: "--strip-components=1"
      become: true

    - name: install rustup
      ansible.builtin.command: "{{ rustup_tempdir.path }}/rustup-init.sh -y"

  when: rustup_download.changed
