---
- name: install steam
  become: yes
  community.general.pacman:
    name: 
      - steam
    state: present

- name: install magohud
  kewlfft.aur.aur:
    name:
      - mangohud
      - lib32-mangohud
    state: present
