---
- name: Install dnsmasq
  ansible.builtin.apt:
    name:
      - dnsmasq
      - dnsmasq-utils
    state: present
  become: true

- name: Configure dnsmasq
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "0644"
    validate: dnsmasq --conf-file=%s --test
  become: true
  notify: Restart dnsmasq

- name: Configure dnsmasq.d/*
  ansible.builtin.copy:
    src: dnsmasq.d/{{ item | basename }}
    dest: /etc/dnsmasq.d/{{ item | basename }}
    owner: root
    group: root
    mode: "0644"
    validate: dnsmasq --conf-file=%s --test
  with_fileglob: dnsmasq.d/*.conf
  become: true
  notify: Restart dnsmasq

- name: Setup tftproot Directory
  ansible.builtin.file:
    path: /srv/tftp
    state: directory
    owner: dnsmasq
    group: netdev
    mode: "0775"
  become: true

#- name: Update selinux context for tftproot
#  community.general.sefcontext:
#    target: /srv/tftp(/.*)?
#    setype: dnsmasq_var_run_t
#    state: present
#  become: true
#  notify: Apply new SELinux file context for tftproot

- name: Enable dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: true
    state: started
  become: true
  notify: Restart dnsmasq

- name: Setup /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart dnsmasq
