---
- name: setup workstation
  hosts: workstations
  roles:
    - chrony
    - fedora
    - firefox
    - fonts
    - rust
    - go
    - vscode
    - steam
    - spotify
    - virtualbox

- name: setup shell enviroment
  hosts: shells
  roles:
    - neovim
    - zsh

- name: setup asus laptop
  hosts: asus
  roles:
    - asus