---
- name: Install packages
  ansible.builtin.apt:
    name:
      - networkd-dispatcher
    state: present
  become: true

- name: Remove old config
  ansible.builtin.file:
    path: /etc/network/interfaces
    state: absent
  become: true

- name: Enable networkd
  ansible.builtin.service:
    name: systemd-networkd
    enabled: true
  become: true

- name: Setup links
  ansible.builtin.template:
    src: link.j2
    dest: /etc/systemd/network/{{ cfg.priority }}-{{ filename }}.link
    owner: root
    group: root
    mode: 0644
  vars:
    filename: "{% if cfg.filename is defined %}{{ cfg.filename }}{% else %}{{ cfg.link.name }}{% endif %}"
  loop: "{{ networkd.links }}"
  loop_control:
    loop_var: cfg
  become: true
  when: networkd.links is defined

- name: Setup netdevs
  ansible.builtin.template:
    src: netdev.j2
    dest: /etc/systemd/network/{{ filename }}.netdev
    owner: root
    group: root
    mode: 0644
  vars:
    filename: "{% if cfg.filename is defined %}{{ cfg.filename }}{% else %}{{ cfg.netdev.name }}{% endif %}"
  loop: "{{ networkd.netdevs }}"
  loop_control:
    loop_var: cfg
  become: true
  when: networkd.netdevs is defined

- name: Setup networks
  ansible.builtin.template:
    src: network.j2
    dest: /etc/systemd/network/{{ filename }}.network
    owner: root
    group: root
    mode: 0644
  vars:
    filename: "{% if cfg.filename is defined %}{{ cfg.filename }}{% else %}{{ cfg.match.name }}{% endif %}"
  loop: "{{ networkd.networks }}"
  loop_control:
    loop_var: cfg
  become: true
