---
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: Add authorized key
  ansible.posix.authorized_key:
    user: "{{ item.unixname }}"
    key: "{{ item.ssh_key }}"
    state: present
  become: true
  loop: "{{ users }}"

- name: Add user
  ansible.builtin.user:
    name: "{{ item.unixname }}"
    shell: /bin/zsh
    groups:
      - sudo
      - adm
      - staff

    append: true
    password: "!"
  become: true
  loop: "{{ users }}"

- name: Configure zsh
  become: true
  ansible.builtin.copy:
    dest: "/home/{{ item.unixname }}/.zshrc"
    content: ""
    owner: "{{ item.unixname }}"
    group: "{{ item.unixname }}"
    mode: "0644"
  loop: "{{ users }}"