---
- name: Install zsh
  ansible.builtin.dnf:
    name: zsh
    state: present
  become: true

- name: Add authorized key
  ansible.posix.authorized_key:
    user: "{{ item.unixname }}"
    key: "{{ item.ssh_key }}"
    state: present
  become: true
  loop: "{{ users }}"

- name: Add user
  ansible.builtin.user:
    name: "{{ item.unixname }}"
    shell: /bin/zsh
    groups: wheel
    append: true
    password: "!"
  become: true
  loop: "{{ users }}"
