---
- name: remove wezterm rpm
  become: true
  ansible.builtin.dnf:
    name: wezterm
    state: absent
    disable_gpg_check: true

- name: download wezterm
  become: true
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "{{ wezterm_url}}"
    dest:  "{{ appimages_dir }}/wezterm.AppImage"
    checksum: "{{ wezterm_checksum }}"
    mode: 0755
  register: wezterm_appimage_dl

- name: link to /usr/local/bin
  become: true
  ansible.builtin.file:
    src: "{{ appimages_dir }}/wezterm.AppImage"
    dest: /usr/local/bin/wezterm
    state: link
    force: true

- name: create wezterm config dir
  ansible.builtin.file:
    path: "{{ wezterm_config_dir }}"
    state: directory
    mode: '0755'

- name: copy wezterm.lua
  ansible.builtin.copy:
    src: wezterm.lua
    dest: "{{ wezterm_config_dir }}/wezterm.lua"
