---
- include_tasks: "{{ ansible_distribution|lower }}.yml" 

- name: add ansible-local
  become: yes
  ansible.builtin.copy:
    src: ansible-local
    dest: /usr/local/bin/ansible-local
    mode: 0755


