---
- name: Include Distro Tasks
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Install ansible-local script
  become: true
  ansible.builtin.copy:
    src: ansible-local
    dest: /usr/local/bin/ansible-local
    mode: 0755
