---
- name: Install sudo
  ansible.builtin.apt:
    name: sudo
  become: true

- name: Configure suoders
  ansible.builtin.copy:
    src: suoders
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  become: true
