---
- name: Install dnf-automatic
  become: true
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Start dnf-automatic timer
  become: true
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
