---
- name: Arch setup
  hosts: arch
  roles:
    - arch
    - gnome

- name: Fedora setup
  hosts: fedora
  roles:
    - fedora
    - gnome

- name: Debian setup
  hosts: debian
  roles:
    - debian

- name: OSX setup
  hosts: osx
  roles:
    - osx

- name: Common workstation
  hosts: all
  roles:
    - ansible
    - git
    - go
    #- neovim
    # - vscode
   # - wezterm
    - zsh
