---
- name: arch setup
  hosts: arch
  roles:
    - arch
    - devel
    - gnome

- name: osx setup
  hosts: osx
  roles:
    - osx

- name: common workstation
  hosts: all
  roles:
    - ansible
    - zsh
    - git
    - neovim
    - wezterm
    - vscode
