---
- name: setup ansible
  hosts: all
  roles: 
    - ansible

- name: setup nvidia drivers
  hosts: nvidia
  roles:
    - nvidia

- name: setup asus laptop
  hosts: asus
  roles:
    - asus

- name: setup shells
  hosts: shells
  roles:
    - git
    - neovim
    - zsh
    - wezterm  # needed on "servers" for multiplexing

- name: setup workstation
  hosts: workstations
  roles:
    - gnome
    - fonts
    # languages
    - rust
    - go
    - nodejs
    # apps
    - discord
    - idea
    - slack
    - spotify
    - virtualbox
    - vscode

- name: setup fb workstation
  hosts: fb_workstations
  roles:
    - dropbox

- name: non fb setup
  hosts: workstations,!fb_workstations
  roles:
    - dnf
    - chrony
