---
- name: setup workstation
  hosts: workstations
  roles:
    - firefox
    - fonts
    - go
    - misc_packages
    - vscode

- name: setup shell enviroment
  hosts: shells
  roles:
    - neovim
    - zsh

- name: setup work laptop
  hosts: subspace
  roles:
    - subspace
