---
- name: setup workstation
  hosts: workstations
  roles:
    - firefox
    - fonts
    - go
    - {role: osx_packages, when: (ansible_distribution|lower == "macosx")}
    - rust
    - vscode

- name: setup shell enviroment
  hosts: shells
  roles:
    - neovim
    - zsh

- name: setup work laptop
  hosts: subspace
  roles:
    - subspace
