---
- name: arch setup
  hosts: arch
  roles:
    - arch
    - ansible
    - zsh
    - git
    - neovim
    - devel

    # gui
    - gnome
    - steam
    - wezterm
    - vscode
    - discord
    - tidal
