- name: OS Setup
  hosts: all
  roles:
    - role: arch
      when: ansible_distribution == "Archlinux"
    - role: fedora
      when: ansible_distribution == "Fedora"
    - name: osx
      when: ansible_distribution == "MacOSX"

- name: Workstation setup
  hosts: workstation
  roles:
    - role: gnome
      when: ansible_system == "Linux"
    - ansible
    - git
    # - neovim
    # - wezterm
    - zsh
