---
- name: Install k3s binary
  become: true
  ansible.builtin.get_url:
    url: "{{ k3s_url }}"
    checksum: "{{ k3s_checksum }}"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  notify: Restart k3s

- name: Add k3s rpm repo (for selinux)
  become: true
  ansible.builtin.yum_repository:
    name: rancher-k3s-common-{{ k3s_rpm_channel }}
    description: Rancher K3 Common ({{ k3s_rpm_channel }})
    baseurl: "{{ k3s_rpm_baseurl }}"
    gpgkey: "{{ k3s_rpm_gpgkey }}"

- name: Install k3s-selinux package
  become: true
  ansible.builtin.dnf:
    name: k3s-selinux
    state: present
  notify: Restart k3s

- name: Setup symlinks
  become: true
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - kubectl
    - crictl
    - ctr

- name: Create k3s config dir
  become: true
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Configure k3s sever
  become: true
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: "0644"
  notify: Restart k3s

- name: Setup cluster token
  become: true
  ansible.builtin.template:
    src: token.j2
    dest: /etc/rancher/k3s/token
    owner: root
    group: root
    mode: "0600"

- name: Setup k3s service
  become: true
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart k3s

- name: Enable k3s service
  become: true
  ansible.builtin.systemd:
    name: k3s
    enabled: true
    daemon_reload: true
  notify: Restart k3s
