---
- name: install nvidia packages
  become: true
  dnf:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      - vdpauinfo
      - libva-vdpau-driver
      - libva-utils
      - vulkan
    state: present
  loop:
