---
- name: install ansible-lint
  become: yes
  ansible.builtin.dnf:
    name: python3-ansible-lint
    state: present
  when:
    # package not present on Centos 8
    - ansible_facts['distribution'] != "CentOS"

- name: install ansible-local
  become: yes
  ansible.builtin.copy:
    src: ansible-local
    dest: /usr/local/bin/ansible-local
    mode: 0755
