---
- name: Download go
  become: true
  ansible.builtin.get_url:
    url: "{{ go_url }}"
    checksum: "{{ go_checksum }}"
    dest: /var/cache/tarballs/{{ go_tarball }}
    owner: root
    group: wheel
    mode: '0644'
  register: go_download

- name: Stat existing directory
  ansible.builtin.stat:
    path: "{{ go_install_dir }}/go"
  register: existing_install

- name: Install Go
  # noqa: no-handler
  when: go_download.changed or not existing_install.stat.exists
  become: true
  block:
    - name: Remove old install
      ansible.builtin.file:
        path: "{{ go_install_dir }}/go"
        state: absent

    - name: Extract tarball
      ansible.builtin.unarchive:
        src: /var/cache/tarballs/{{ go_tarball }}
        dest: "{{ go_install_dir }}"
