---
- name: Create tarball directory
  become: true
  ansible.builtin.file:
    path: /var/cache/tarballs
    state: directory
    owner: root
    group: "{{ admin_group }}"
    mode: "0755"

- name: Cleanup tarball directory
  block:
    - name: Find old files
      ansible.builtin.find:
        paths: /var/cache/tarballs
        age: 12w
      register: old_tarballs

    - name: Remove old tarballs
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_tarballs.files }}"
