---
- name: install packages (arch)
  block:
    - name: install zsh
      become: yes
      community.general.pacman:
        name: 
          - zsh
          - zsh-completions
        state: present
    - name: install powerline-go (arch)
      kewlfft.aur.aur:
        name: powerline-go
        state: present
  when: ansible_facts['distribution'] == "Arch"

- name: install packages (mac)
  community.general.homebrew:
    name: powerline-go
  when: ansible_facts['distribution'] == "MacOSX"

- name: change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- name: copy .zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: copy .zshrc.d
  ansible.posix.synchronize:
    src: zshrc.d/
    dest: "{{ ansible_env.HOME }}/.zshrc.d/"
    recursive: true
    delete: true

