---
- name: Install Packages
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ main_user_unixname }}"
    shell: /bin/zsh

- name: Copy .zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ main_user_home }}/.zshrc"
    owner: "{{ main_user_unixname }}"
    group: "{{ main_user_group }}"
    mode: "0644"

- name: Copy .zshrc.d
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ main_user_home }}/.zshrc.d/"
    owner: "{{ main_user_unixname }}"
    group: "{{ main_user_group }}"
    mode: "0644"
  with_fileglob: zshrc.d/*
