---
- name: install zsh
  become: true
  ansible.builtin.dnf:
    name: zsh
    state: present

- name: change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ user_id}}"
    shell: /bin/zsh

- name: copy .zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ user_home }}/.zshrc"

- name: copy .zshrc.d
  ansible.builtin.synchronize:
    src: zshrc.d/
    dest: "{{ user_home }}/.zshrc.d/"
    recursive: true
    delete: true

- name: remove powerline-go system packages
  become: yes
  ansible.builtin.dnf:
    name: powerline-go
    state: absent

- name: install powerline-go
  become: yes
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "{{ powerline_go_url }}"
    dest: /usr/local/bin/powerline-go
    mode: 0755
    
