
- name: install packages
  include: "install_{{ ansible_distribution|lower }}.yml"

- name: change user shell to zsh 
  become: yes
  user:
    name: "{{ user_id}}"
    shell: /bin/zsh

- name: copy .zshrc
  copy:
    src: zshrc
    dest: "{{ user_home }}/.zshrc"

- name: copy .zshrc.d
  synchronize:
    src: zshrc.d/
    dest: "{{ user_home }}/.zshrc.d/"
    recursive: yes
    delete: yes
