---
- name: core setup
  hosts: all
  roles:
    - sudo # sudo needs to be first
    - hostname
    - users
    - epel
    - ipmi
    - ixgbe
    - networkd
    - dnf
    - chrony
    - utils
    - node_exporter

- name: firewall setup
  hosts: fw
  roles:
    - nextdns
    - dnsmasq
    - mdnsrepeater
    - ip_forward
    - nftables
    - ddns
    - bird

- name: kube setup
  hosts: kube
  roles:
    - k3s
