- name: core setup
  hosts: all
  roles:
    - hostname
    - hosts
    - users
    - sudo
    - epel
    - ixgbe
    - networkd
    - dnf
    - chrony
    - utils
  
- name: firewall setup
  hosts: fw
  roles: 
    - dnsmasq 
    - mdnsrepeater
    - ip_forward
    - nftables