---
- name: core setup
  hosts: all
  roles:
    - sudo
    - users
    - apt
    - hostname
    - ixgbe
    - networkd
    - chrony
    - utils
    - node_exporter

- name: firewall setup
  hosts: fw
  roles:
    - ip_forward
    - nftables
    - dnsmasq
    - nextdns
    - bird
    - mdns-reflector

- name: kube setup
  hosts: kube
  roles:
    - k3s

- name: tank setup
  hosts: tank
  roles:
    - zfs
    - nfs
    - samba

