---
- name: core setup
  hosts: all
  roles:
    - sudo # sudo needs to be first
    - apt
    - hostname
    - users
    - ixgbe
    - networkd
    - chrony
    - utils
    - node_exporter

- name: firewall setup
  hosts: fw
  roles:
    - ip_forward
    - nftables
    - dnsmasq
    - nextdns
    - bird
    - mdns-reflector

- name: kube setup
  hosts: kube
  roles:
    - k3s
