---
- name: install flatpak
  community.general.flatpak:
    name: com.spotify.Client
    state: present

- name: remove lpf client
  become: true
  ansible.builtin.dnf:
    name: lpf-spotify-client
    state: absent