---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name: apt-transport-https

- name: Configure sources
  become: true
  ansible.builtin.template:
    src: debian.sources.j2
    dest: /etc/apt/sources.list.d/debian.sources
    owner: root
    group: root
    mode: "0644"
  vars:
    debian_codename: "{{ ansible_lsb.codename }}"
  notify: Update apt cache

- name: Remove old sources.list
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent
