- name: remove powerline-go system packages
  become: yes
  ansible.builtin.dnf:
    name: powerline-go
    state: absent

- name: download powerline-go
  become: yes
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "{{ powerline_go_url }}"
    dest: "{{ appimages_dir }}/powerline-go.AppImage"
    mode: 0755
    checksum: "{{ powerline_go_checksum }}"

- name: symlink powerline-go to /usr/local/bin
  become: yes
  ansible.builtin.file :
    src: "{{ appimages_dir }}/powerline-go.AppImage"
    dest: "/usr/local/bin/powerline-go"
    state: link
    force: true