---
- name: Install Packages
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Configure git
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ main_user_home }}/.gitconfig"
    owner: "{{ main_user_unixname }}"
    group: "{{ main_user_group }}"
    mode: "0644"
    backup: true
