---
- name: configure gdm
  become: yes
  ansible.builtin.template:
    src: gdm_custom.conf.j2
    dest: /etc/gdm/custom.conf
    backup: yes


- name: install tweaks
  become: yes
  ansible.builtin.dnf:
    name: gnome-tweaks
    state: present

- name: set xkb-options
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['lv3:ralt_switch', 'ctrl:nocaps']"

- name: set media keys
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - {key: "previous", value: "['<Super>comma']"}
    - {key: "next", value: "['<Super>period']"}
    - {key: "play", value: "['<Super>slash']"}