---
- name: Install Node Exporter
  become: true
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Enable prometheus-node-exporter service
  become: true
  ansible.builtin.systemd:
    name: prometheus-node-exporter.service
    enabled: true
    state: started
