---
- import_tasks: homebrew.yml

- name: turn off desktop icons
  community.general.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false
    state: present

- name: install packages
  community.general.homebrew:
    name:
      - colordiff
      - coreutils
      - gh
      - gnu-tar
      - htop
      - kubectl
      - powerline-go
      - watch
      - xz
      - zsh-completions
      # languages
      - golang
      - rustup
      - zig
      # hashicrap^H^H^H^Hstack
      - consul
      - nomad
      - vault

- name: install applications
  community.general.homebrew_cask:
    name:
      - bitwarden
      - discord
      - firefox
      - google-drive
      - iterm2
      - karabiner-elements
      - parallels
      - protonmail-bridge
      - raycast
      - rectangle
      - slack
      - spotify
      - steam
      - whatsapp
      - zoom
      # fonts
      -  homebrew/cask-fonts/font-meslo-for-powerline
