---
- import_tasks: homebrew.yml

- name: turn off desktop icons
  community.general.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false
    state: present

- name: install packages
  community.general.homebrew:
    name:
      - bat
      - colordiff
      - coreutils
      - duf
      - fd
      - gh
      - gnu-tar
      - htop
      - httpie
      - iperf
      - jq
      - kubectl
      - make
      - mtr
      - ncdu
      - nmap
      - powerline-go
      - procs
      - scc
      - sqlite
      - tldr
      - tree
      - watch
      - xz
      - zsh-completions
      # languages
      - golang
      - rustup
      - zig
      - node
      # hashicrap^H^H^H^Hstack
      - consul
      - nomad
      - vault

- name: install applications
  community.general.homebrew_cask:
    name:
      - alt-tab
      - autodesk-fusion360
      - bitwarden
      - discord
      - firefox
      - google-drive
      - httpie
      - iterm2
      - karabiner-elements
      - logseq
      - parallels
      - protonmail-bridge
      - prusaslicer
      - raycast
      - rectangle
      - shottr
      - slack
      - spotify
      - steam
      - superslicer
      - whatsapp
      - zoom
      # fonts
      - homebrew/cask-fonts/font-meslo-for-powerline
