---
- name: Setup Homebrew
  ansible.builtin.import_tasks: homebrew.yml

- name: Turn off desktop icons
  community.general.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false
    state: present

- name: Remove old packages
  community.general.homebrew:
    state: absent
    name:
      - powerline-go  # replaced by oh-my-posh
      - exa           # no longer supported

- name: Install packages
  community.general.homebrew:
    name:
      - awscli
      - bat
      - black
      - broot
      - colordiff
      - coreutils
      - duf
      - eza
      - fd
      - gh
      - gnu-tar
      - htop
      - httpie
      - iperf
      - jq
      - kubectl
      - make
      - mtr
      - ncdu
      - nmap
      - postgresql@13
      - powerline-go
      - procs
      - scc
      - sqlite
      - tldr
      - tree
      - watch
      - xz
      - zsh-completions
      - zstd
      # languages
      - golangci-lint
      - gofumpt
      - node
      - pipx
      - rustup
      - zig
      # hashicrap^H^H^H^Hstack
      - consul
      - nomad
      - vault
      # bazel
      - bazelisk
      - buildifier
      - buildozer


- name: Remove no longer used applications
  community.general.homebrew_cask:
    state: absent
    name:
      - superslicer            # replaced by orcaslicer
      - prusaslicer            # replaced by orcaslicer
      - softfever-bambu-studio # replaced by orcaslicer
      - shottr                 # i don't OCR like @coxley
      - parallels              # Too much $$
      - protonmail-bridge      # use fastmail now
      - iterm2                 # https://gitlab.com/gnachman/iterm2/-/issues/11470

- name: Install applications
  community.general.homebrew_cask:
    name:
      - alt-tab
      - autodesk-fusion360
      - bambu-studio
      - bitwarden
      - discord
      - docker
      - firefox
      - geekbench
      - google-drive
      - httpie
      - istat-menus
      - iterm2
      - karabiner-elements
      - logseq
      - menuwhere
      - orcaslicer
      - raycast
      - rectangle
      - slack
      - spotify
      - steam
      - unnaturalscrollwheels  # mouse go up, trackpad go down
      - utm
      - whatsapp
      - wireshark
      - zoom
      # fonts
      - font-meslo-for-powerline
      - font-blex-mono-nerd-font

