---
- name: install packages (arch)
  become: yes
  community.general.pacman:
    name: wezterm
    state: present
  when: ansible_facts['distribution'] == "Arch"

- name: install packages (osx)
  community.general.homebrew_cask:
    name: wezterm
  when: ansible_facts['distribution'] == "MacOSX"

- name: create wezterm config dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/wezterm"
    state: directory
    mode: "0755"

- name: configure wezterm
  ansible.builtin.copy:
    src: wezterm.lua
    dest: "{{ ansible_env.HOME }}/.config/wezterm/wezterm.lua"
