---
- name: install libsecret credential helper
  become: yes
  ansible.builtin.dnf:
    name: git-credential-libsecret
    state: present

- name: git configuration
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ user_home }}/.gitconfig"
    backup: yes
