---
- name: install wezterm
  become: true
  environment: "{{ proxy_env }}"
  ansible.builtin.dnf:
    name: "{{ wezterm_rpm_url }}"
    state: present
    disable_gpg_check: true
    
- name: create wezterm config dir
  ansible.builtin.file:
    path: "{{ wezterm_config_dir }}"
    state: directory
    mode: '0755'

- name: copy wezterm.lua
  ansible.builtin.copy:
    src: wezterm.lua
    dest: "{{ wezterm_config_dir }}/wezterm.lua"
