---
- name: download wezterm
  become: true
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "{{ wezterm_rpm_url }}"
    dest: "{{ wezterm_rpm }}"
    checksum: "{{ checksums[wezterm_rpm|basename] }}"
  
- name: install wezterm
  become: true
  ansible.builtin.dnf:
    name: "{{ wezterm_rpm }}"
    state: present
    disable_gpg_check: true
    
- name: create wezterm config dir
  ansible.builtin.file:
    path: "{{ wezterm_config_dir }}"
    state: directory
    mode: '0755'

- name: copy wezterm.lua
  ansible.builtin.copy:
    src: wezterm.lua
    dest: "{{ wezterm_config_dir }}/wezterm.lua"
