---
- name: download go
  get_url:
    url: "{{ go_url }}"
    dest: "{{ go_tarball }}"
    checksum: "{{ checksums[go_tarball|basename] }}"
  become: true

- name: create versioned directory
  file:
    path: /opt/go{{ go_version }}
    state: directory
    mode: '0755'
  become: true

- name: extract go
  unarchive:
    src: "{{ go_tarball }}"
    dest: /opt/go{{ go_version }}
    extra_opts: "--strip-components=1"
  register: go_versioned_dir
  become: true

- name: remove old symlink
  file:
    path: /opt/go
    state: absent
  become: true
  when: go_versioned_dir.changed

- name: link new version
  file:
    src: /opt/go{{ go_version }}
    dest:  /opt/go
    state:  link
  become: true
  when: go_versioned_dir.changed


