---
- name: Enable asus copr repo
  become: true
  community.general.copr:
    name: lukenukem/asus-linux

- name: Install asus package
  become: true
  ansible.builtin.dnf:
    name:
      - asusctl
      - supergfxctl
