---
- name: install rpmfusion gpg keys
  become: yes
  ansible.builtin.rpm_key:
    key: "{{ item }}"
  loop:
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: add rpmfusion reposiories
  become: yes
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm 
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm 

- name: install openconnect copr
  become: yes
  community.general.copr:
    name: "dwmw2/openconnect"

- name: add github cli repo
  become: yes
  ansible.builtin.yum_repository:
    name: gh-cli
    description: packages for the GitHub CLI
    baseurl: https://cli.github.com/packages/rpm
    enabled: yes
    gpgkey: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc99b11deb97541f0

- name: add hashicorp repos
  become: yes
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: install packages
  become: yes
  ansible.builtin.dnf:
    name:
      # cli utilities
      - most
      - htop
      - mosh
      - git
      - git-lfs
      - gh

      # drivers / etc
      - vulkan
      - vdpauinfo
      - libva-vdpau-driver
      - libva-utils
      - intel-media-driver
      - "@multimedia"
      - "@sound-and-video"
      - "@Development Tools"

      # gui
      - vlc
      - gnome-tweak-tool
      - gnome-extensions-app
      - steam

      # fonts
      - google-roboto-condensed-fonts
      - google-roboto-fonts
      - google-roboto-mono-fonts
      - google-roboto-slab-fonts
      - fira-code-fonts
      - mozilla-fira-fonts-common
      - mozilla-fira-mono-fonts
      - mozilla-fira-sans-fonts
      - adobe-source-code-pro-fonts

      # hashicorp
      - nomad
      - vault
      - consul

- name: enable flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: install flatpaks
  become: yes
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.slack.Slack
      - com.spotify.Client
      - io.typora.Typora
      - us.zoom.Zoom

- name: i915 module config
  become: yes
  ansible.builtin.copy:
    src: modprobe/i915.conf
    dest: /etc/modprobe.d/i915.conf
    owner: root
    group: root
    mode: '0644'
  notify: regenerate initramfs

- import_tasks: dnf.yml
- import_tasks: asus_g14.yml
  when: asus_g14 is defined
- import_tasks: nvidia.yml
  when: nvidia is defined
