---
- name: install nvidia packages
  become: yes
  ansible.builtin.dnf:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda

- name: nvidia module config
  become: yes
  ansible.builtin.copy:
    src: modprobe/nvidia.conf
    dest: /etc/modprobe.d/nvidia.conf
    owner: root
    group: root
    mode: "0644"
  notify: regenerate initramfs
