---
- name: Install podman packages
  become: true
  ansible.builtin.dnf:
    name:
      - podman
      - docker-compose

- name: Enable podman service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: podman.socket
