---
- name: Install asus_g14 packages
  become: true
  community.general.pacman:
    name:
      - asusctl
      - supergfxctl
      - acpi_call
      - rog-control-center

- name: Enable power-profiles-daemon.service
  become: true
  ansible.builtin.systemd:
    name: power-profiles-daemon.service
    state: started
    enabled: true

- name: Enable supergfxd.service
  become: true
  ansible.builtin.systemd:
    name: supergfxd.service
    state: started
    enabled: true
