---
- name: Install bluetooth packages
  become: true
  community.general.pacman:
    name:
      - bluez
      - bluez-utils

- name: Enable bluetooth.service
  become: true
  ansible.builtin.systemd:
    name: bluetooth.service
    enabled: true
  notify: Restart bluetooth.service

- name: Configure bluetooth
  become: true
  ansible.builtin.copy:
    src: bluetooth-main.conf
    dest: /etc/bluetooth/main.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart bluetooth.service
