---
- name: Install development packages
  become: true
  community.general.pacman:
    name:
      - nodejs
      - rustup
      - zig
    state: present

- name: Set rustup default toolchain
  become: "{{ main_user_unixname }}"
  ansible.builtin.command:
    cmd: rustup default stable
    creates: "{{ main_user_home }}/.rustup/settings.toml"
