---
- name: Install development packages
  become: true
  community.general.pacman:
    name:
      - nodejs
      - rustup
      - zig
      - go
      - github-cli
    state: present

- name: Install development packages (aur)
  kewlfft.aur.aur:
    name:
      - gleam-bin
    state: present

- name: Set rustup default toolchain
  become: true
  become_user: "{{ main_user_unixname }}"
  ansible.builtin.command:
    cmd: rustup default stable
    creates: "{{ main_user_home }}/.rustup/settings.toml"
