---
- name: Setup pacman
  become: true
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    mode: 0644
  notify: Refresh pacman database

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Install packages
  become: true
  community.general.pacman:
    name:
      # tools
      - acpi
      - bind # for dig
      - dmidecode
      - fwupd
      - git
      - htop
      - man
      - most
      - pkgfile
      - plocate
      - rsync
      - strace
      - base-devel
      - wget
      - ranger

      # applications
      - firefox
      - discord
      - steam

      # graphics
      - libva-utils
      - vdpauinfo
      - vulkan-tools

      # fonts
      - adobe-source-code-pro-fonts
      - cantarell-fonts
      - noto-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-liberation
      - ttf-carlito
      - gsfonts

- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install aur packages
  kewlfft.aur.aur:
    name:
      - tidal-hifi-bin
      - mangohud
      - lib32-mangohud
    state: present

- name: Enable fstrim.service
  become: true
  ansible.builtin.systemd:
    name: fstrim.service
    enabled: true

- name: Configure systemd
  ansible.builtin.import_tasks: systemd.yml

- name: Configure bluetooth
  ansible.builtin.import_tasks: bluetooth.yml

- name: Configure Development Environment
  ansible.builtin.import_tasks: devel.yml

- name: Configure Asus G14
  ansible.builtin.import_tasks: asus_g14.yml
  when: asus_g14 is defined

- name: Configure NVIDIA
  ansible.builtin.import_tasks: nvidia.yml
  when: nvidia is defined
