---
- name: Setup pacman
  become: true
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    mode: 0644
  notify: Refresh pacman database

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Install packages
  become: true
  community.general.pacman:
    name:
      # tools
      - acpi
      - base-devel
      - bind # for dig
      - dmidecode
      - fwupd
      - git
      - htop
      - man
      - most
      - ncdu
      - neofetch
      - pkgfile
      - plocate
      - ranger
      - ripgrep
      - rsync
      - socat
      - strace
      - wget
      - kubectl
      - tree
      - bat
      - broot
      - mtr
      - colordiff
      - duf
      - fd
      - iperf3
      - nmap
      - procs
      - sqlite
      - tldr

      # applications
      - discord
      - firefox
      - libreoffice 
      - steam
      - wezterm

      # graphics
      - libva-utils
      - vdpauinfo
      - vulkan-tools

      # fonts
      - adobe-source-code-pro-fonts
      - cantarell-fonts
      - noto-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-liberation
      - ttf-carlito
      - gsfonts

- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install aur packages
  kewlfft.aur.aur:
    name:
      - mangohud
      - lib32-mangohud
      - slack-desktop
      - librewolf-bin
    state: present

- name: Enable fstrim.service
  become: true
  ansible.builtin.systemd:
    name: fstrim.service
    enabled: true

- name: Configure systemd
  ansible.builtin.import_tasks: systemd.yml

- name: Configure bluetooth
  ansible.builtin.import_tasks: bluetooth.yml

- name: Configure Avahi
  ansible.builtin.import_tasks: avahi.yml

- name: Configure CUPS
  ansible.builtin.import_tasks: cups.yml

- name: Configure tuned
  ansible.builtin.import_tasks: tuned.yml

- name: Configure Development Environment
  ansible.builtin.import_tasks: devel.yml

- name: Configure NVIDIA
  ansible.builtin.import_tasks: nvidia.yml
  when: nvidia is defined

