---
# Update the systemd-boot bootloader when the package has been updated
# https://wiki.archlinux.org/title/Systemd-boot#systemd_service
- name: Enable systemd-boot-update service
  become: true
  ansible.builtin.systemd:
    name: systemd-boot-update.service
    enabled: true

- name: Enable systemd-timesyncd
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    enabled: true
  notify: Restart systemd-timesyncd.service

- name: Configure systemd-timesyncd
  become: true
  ansible.builtin.copy:
    src: systemd-timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart systemd-timesyncd.service
