---
- name: install utils
  ansible.builtin.dnf:
    name:
      - bind-utils # dig
      - htop
      - lsof
      - nmap
      - pciutils
      - screen
      - smartmontools
      - tar
      - tcpdump
      - wget
    state: present
  become: yes
