---
- name: Refresh pacman database
  become: true
  community.general.pacman:
    update_cache: true

- name: Restart bluetooth.service
  become: true
  ansible.builtin.systemd:
    name: bluetooth.service
    state: restarted

- name: Restart systemd-timesyncd.service
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: restarted
