---
- name: install dropbox
  become: true
  ansible.builtin.dnf:
    name: https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2020.03.04-1.fedora.x86_64.rpm
    state: present
    disable_gpg_check: true