---
- name: dowload dropbox
  become: true
  ansible.builtin.get_url:
    url: "{{ dropbox_url }}"
    dest: "{{ dropbox_rpm }}"
    checksum: "{{ dropbox_checksum }}"

- name: install dropbox
  become: true
  ansible.builtin.dnf:
    name: "{{ dropbox_rpm }}"
    state: present
    disable_gpg_check: true