---
- name: Install packagees
  become: true
  community.general.pacman:
    name:
      - gdm
      - gimp # image editor
      - gnome
      - gnome-firmware # frontend for fwupd
      - gnome-todo
      - gnome-tweaks
      - python-psutil # needed for dconf module below
      - gnome-software-packagekit-plugin
      - ttf-fira-code
    state: present

- name: Enable gdm
  become: true
  ansible.builtin.systemd:
    name: gdm.service
    enabled: true
