---
- name: Install packagees
  become: true
  community.general.pacman:
    name:
      - gdm
      - geary # email
      - gimp # image editor
      - gnome
      - gnome-firmware # frontend for fwupd
      - gnome-todo
      - gnome-tweaks
      - gvfs-afc
      - gvfs-dnssd
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - gvfs-wsdd
      - python-psutil # needed for dconf module below
      - seahorse
      - ttf-fira-code
    state: present

- name: Enable gdm
  become: true
  ansible.builtin.systemd:
    name: gdm.service
    enabled: true
