---
- name: Iinstall microsoft gpg keys
  become: true
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add vscode repos
  become: true
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode

- name: Install packages
  become: true
  ansible.builtin.dnf:
    name: code
