---
- name: install packages
  include: "install_{{ ansible_distribution|lower }}.yml"

- name: install vscode extensions
  vscode_ext:
    name: "{{ item }}"
    state: present
  loop:
    - bbenoist.vagrant
    - golang.go
    - ms-vscode-remote.vscode-remote-extensionpack
    - rust-lang.rust
    - vscodevim.vim
    - ms-python.python
