---
- name: Install VSCode
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Install vscode extentions
  vscode_ext:
    name: "{{ item }}"
    state: present
  loop:
    - AugusteRame.zls-vscode
    - aaron-bond.better-comments
    - atlassian.atlascode
    - bbenoist.vagrant
    - foxundermoon.shell-format
    - gimenete.github-linker
    - golang.go
    - meta.sapling-scm
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-vscode.cpptools
    - phgn.vscode-starlark
    - redhat.vscode-yaml
    - rust-lang.rust-analyzer
    - stkb.rewrap
    - tiehuis.zig
    - timonwong.shellcheck
    - vscodevim.vim
