---
- name: install packages (arch)
  kewlfft.aur.aur:
    name: visual-studio-code-bin 
    state: present
  when: ansible_facts['distribution'] == "Arch"

- name: install packages (osx)
  community.general.homebrew_cask:
    name: visual-studio-code
  when: ansible_facts['distribution'] == "MacOSX"

- name: install vscode extentions
  vscode_ext:
    name: "{{ item }}"
    state: present
  loop:
    - AugusteRame.zls-vscode
    - bbenoist.vagrant
    - golang.go
    - ms-python.python
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-vscode.cpptools
    - phgn.vscode-starlark
    - matklad.rust-analyzer
    - tiehuis.zig
    - vscodevim.vim
