---
- name: add vscode repo
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: install vscode
  become: yes
  dnf:
    name: code
    state: present

- name: install vscode extensions
  vscode_ext:
    name: "{{ item }}"
    state: present
  loop:
    - bbenoist.vagrant
    - golang.go
    - ms-vscode-remote.vscode-remote-extensionpack
    - rust-lang.rust
    - vscodevim.vim
    - ms-python.python
