---
- name: download zig
  become: true
  get_url:
    url: "{{ zig_url }}"
    dest: "{{ zig_tarball }}"
    checksum: "{{ zig_checksum }}"

- name: create versioned directory
  become: true
  file:
    path: /opt/zig-{{ zig_version }}
    state: directory
    mode: '0755'

- name: extract zig 
  become: true
  unarchive:
    src: "{{ zig_tarball }}"
    dest: /opt/zig-{{ zig_version }}
    extra_opts: "--strip=1"
  register: zig_versioned_dir

- name: remove old symlink
  become: true
  file:
    path: /opt/zig
    state: absent
  when: zig_versioned_dir.changed

- name: link new version
  become: true
  file:
    src: /opt/zig-{{ zig_version }}
    dest:  /opt/zig
    state:  link
  when: zig_versioned_dir.changed

- name: download zls
  become: true
  get_url:
    url: "{{ zls_url }}"
    dest: "{{ zls_tarball }}"
    checksum: "{{ zls_checksum }}"
    mode: 0644

- name: extract zls
  become: true
  unarchive:
    src: "{{ zls_tarball }}"
    dest: /opt/zig-{{ zig_version }}
    extra_opts: 
      - "--strip=1"
      - "--no-anchored"
      - "zls"

- name: zls permissions
  become: true
  file:
    path: /opt/zig-{{ zig_version }}/zls
    mode: 0755
