---
- name: Add GPG key
  become: true
  ansible.builtin.get_url:
    url: https://repo.nextdns.io/nextdns.gpg
    dest: /etc/apt/keyrings/nextdns.gpg
    mode: '0644'

- name: Add nextdns repos
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main
    filename: nextdns

- name: Install nextdns proxy
  become: true
  ansible.builtin.apt:
    name: nextdns

- name: Configure nextdns proxy
  become: true
  ansible.builtin.copy:
    src: nextdns.conf
    dest: /etc/nextdns.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart nextdns

- name: Setup nextdns service
  become: true
  ansible.builtin.copy:
    src: nextdns.service
    dest: /etc/systemd/system/nextdns.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart nextdns

- name: Enable nextdns service
  become: true
  ansible.builtin.systemd:
    name: nextdns
    enabled: true
    daemon_reload: true
  notify: Restart nextdns
