---
- name: Install Packages
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Create paq directory
  ansible.builtin.file:
    path: "{{ main_user_home }}/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    state: directory
    mode: "0755"

- name: Download paq
  ansible.builtin.get_url:
    url: https://github.com/savq/paq-nvim/archive/refs/tags/v1.0.2.tar.gz
    dest: "{{ main_user_home }}/.local/share/nvim/paq-1.0.2.tar.gz"
    owner: "{{ main_user_unixname }}"
    group: "{{ main_user_group }}"
    mode: "0644"

- name: Install paq
  ansible.builtin.unarchive:
    src: "{{ main_user_home }}/.local/share/nvim/paq-1.0.2.tar.gz"
    dest: "{{ main_user_home }}/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    extra_opts: --strip-components=1
    owner: "{{ main_user_unixname }}"
    group: "{{ main_user_group }}"

- name: Create nvim config directory
  ansible.builtin.file:
    path: "{{ main_user_home }}/.config/nvim"
    state: directory
    owner: "{{ main_user_unixname }}"
    group: "{{ main_user_group }}"
    mode: "0755"

- name: Copy nvim config
  ansible.builtin.copy:
    src: init.lua
    dest: "{{ main_user_home }}/.config/nvim/init.lua"
    owner: "{{ main_user_unixname }}"
    group: "{{ main_user_group }}"
    mode: "0644"
