---
- name: install neovim packages
  become: true
  dnf:
    name:
      - neovim
      - python3-neovim
    state: present
  loop:

- name: copy nvim config
  copy:
    src: config/
    dest: "{{ user_home }}/.config/nvim"
