---
- name: download idea 
  become: true
  ansible.builtin.get_url:
    url: "{{ idea_url }}"
    dest: "{{ idea_tarball }}"
    checksum: "{{ idea_checksum }}"

- name: create versioned directory
  become: true
  ansible.builtin.file:
    path: /opt/idea-IC-{{ idea_version }}
    state: directory
    mode: '0755'

- name: extract idea
  become: true
  ansible.builtin.unarchive:
    src: "{{ idea_tarball }}"
    dest: /opt/idea-IC-{{ idea_version }}
    extra_opts: "--strip-components=1"
  register: idea_versioned_dir

- name: remove old symlink
  become: true
  ansible.builtin.file:
    path: /opt/idea
    state: absent
  when: idea_versioned_dir.changed

- name: link new version
  become: true
  ansible.builtin.file:
    src: /opt/idea-IC-{{ idea_version }}
    dest:  /opt/idea
    state:  link
  when: idea_versioned_dir.changed

- name: add desktop icon
  become: true
  ansible.builtin.copy:
    src: jetbrains-idea-ce.desktop
    dest: /usr/local/share/applications/jetbrains-idea-ce.desktop
