---
- name: Install chrony
  become: true
  notify: Restart chronyd
  ansible.builtin.dnf:
    name: chrony
    state: present

- name: Enable chronyd service
  become: true
  ansible.builtin.systemd:
    name: chronyd
    enabled: true

- name: Configure chrony
  become: true
  notify: Restart chronyd
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    trim_blocks: false
