---
- name: Install packages
  ansible.builtin.apt:
    name:
      - samba
      - samba-client
      - wsdd2
  become: true

- name: Configure samba sever
  become: true
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
    validate: /usr/bin/testparm -s %s
  vars:
    netbios_name: "{{ ansible_hostname }}"
  notify: 
   - Restart samba
   - Restart wsdd2
  

- name: Enable samaba
  become: true
  ansible.builtin.systemd:
    name: samba
    enabled: true
  notify: Restart samba

- name: Enable wsdd2
  become: true
  ansible.builtin.systemd:
    name: wsdd2
    enabled: true
  notify: Restart wsdd2
