go_version: "{{ versions['go'] }}"

go_arch_map:
  "x86_64": "amd64"
go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

go_os_map:
  "Linux": "linux"
go_os: "{{ go_os_map[ansible_system] | default(ansible_system|lower) }}"

go_tarball: "{{ packages_cache_dir }}/go{{ go_version }}.{{go_os}}-{{go_arch}}.tar.gz"
go_url: https://golang.org/dl/{{ go_tarball|basename }}