---
- name: Remove old config
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nftables/nat.nft
    - /etc/nftables/router.nft

- name: Configure nftables
  ansible.builtin.copy:
    src: main.nft
    dest: /etc/nftables/main.nft
    owner: root
    group: root
    mode: 0600
    validate: nft --file %s --check
  become: true
  notify: Restart nftables

- name: Configure entry config
  ansible.builtin.copy:
    src: nftables.conf
    dest: /etc/sysconfig/nftables.conf
    owner: root
    group: root
    mode: 0600
    validate: nft --file %s --check
  become: true
  notify: Restart nftables

- name: Disable firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  become: true

- name: Enable nftables service
  ansible.builtin.service:
    name: nftables
    enabled: true
  become: true
  notify: Restart nftables
