---
- name: Configure nftables
  ansible.builtin.copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0600
    validate: nft --file %s --check
  become: true
  notify: Restart nftables

- name: Enable nftables service
  ansible.builtin.service:
    name: nftables
    enabled: true
  become: true
  notify: Restart nftables
